sudo: required
dist: trusty
language: python
virtualenv:
 system_site_package: false

install:
  - pip install pipenv pew

script:
  - bash -xve ./test/travis_ros_install.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_package_make.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_prepare_dummy_files.bash
#  - rostest pimouse_ros test_buzzer.launch
  - rostest pimouse_ros test.launch
